In [11]:
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=0)
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
df=pd.read_csv('Churn.csv')

dz=df[df.Churn> 0]
dx=df.append(dz)
print(df.shape, dz.shape, dx.shape)

#print(df.groupby('Churn').count())
dx=np.array(dx)
display(dx)
np.random.shuffle(dx)

#print(df.groupby[:,0].sum())
X=dx[:, 1:] 
y=dx[:, 0]

#_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=1/4)

#X_train_s, y_train_s=smote.fit_sample(X_train, y_train)
#clf1 = svm.SVC()
#clf2 = GaussianNB()
clf3 = AdaBoostClassifier()
clf4 = GradientBoostingClassifier()
clf5 = XGBClassifier()
clf1 = DecisionTreeClassifier()
clf2 = RandomForestClassifier()
for i in range(1):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/4,random_state=0)
#    X_train_s, y_train_s=smote.fit_sample(X_train, y_train)
    for clf in [clf1, clf2, clf3, clf4, clf5]:
        clf.fit(X_train, y_train)
        print(clf,"full 변수 정확도:")
        print(clf.score(X_test, y_test))
        print("\n")


(3333, 17) (483, 17) (3816, 17)


array([[  0.  ,  25.  , 265.1 , ...,  11.01,   3.  ,   2.7 ],
       [  0.  ,  26.  , 161.6 , ...,  11.45,   3.  ,   3.7 ],
       [  0.  ,   0.  , 243.4 , ...,   7.32,   5.  ,   3.29],
       ...,
       [  1.  ,   0.  , 140.  , ...,   5.4 ,   4.  ,   2.62],
       [  1.  ,   0.  , 321.1 , ...,   8.12,   2.  ,   3.11],
       [  1.  ,   0.  , 118.4 , ...,  10.22,   3.  ,   3.67]])

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best') full 변수 정확도:
0.9549266247379455


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False) full 변수 정확도:
0.9643605870020965




C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None) full 변수 정확도:
0.8375262054507338


GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False) full 변수 정확도:
0.9371069182389937


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bytree=1, gamma=0, learning_

In [12]:
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=0)
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
df=pd.read_csv('Churn.csv')

dz=df[df.Churn> 0]
dx=df.append(dz)
print(df.shape, dz.shape, dx.shape)

#print(df.groupby('Churn').count())
dx=np.array(dx)
display(dx)
np.random.shuffle(dx)

#print(df.groupby[:,0].sum())
X=dx[:, 1:] 
y=dx[:, 0]

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=1/4)

X_train_s, y_train_s=smote.fit_sample(X_train, y_train)
#clf1 = svm.SVC()
#clf2 = GaussianNB()
clf3 = AdaBoostClassifier()
clf4 = GradientBoostingClassifier()
clf5 = XGBClassifier()
clf1 = DecisionTreeClassifier()
clf2 = RandomForestClassifier()
for i in range(1):
    X_train, X_test, y_train, y_test = train_test_split(X_train_s, y_train_s, test_size=1/4,random_state=0)
    #    X_train_s, y_train_s=smote.fit_sample(X_train, y_train)
    for clf in [clf1, clf2, clf3, clf4, clf5]:
        clf.fit(X_train, y_train)
        print(clf,"full 변수 정확도:")
        print(clf.score(X_test, y_test))
        print("\n")


(3333, 17) (483, 17) (3816, 17)


array([[  0.  ,  25.  , 265.1 , ...,  11.01,   3.  ,   2.7 ],
       [  0.  ,  26.  , 161.6 , ...,  11.45,   3.  ,   3.7 ],
       [  0.  ,   0.  , 243.4 , ...,   7.32,   5.  ,   3.29],
       ...,
       [  1.  ,   0.  , 140.  , ...,   5.4 ,   4.  ,   2.62],
       [  1.  ,   0.  , 321.1 , ...,   8.12,   2.  ,   3.11],
       [  1.  ,   0.  , 118.4 , ...,  10.22,   3.  ,   3.67]])

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best') full 변수 정확도:
0.9290382819794585


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False) full 변수 정확도:
0.9551820728291317




C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None) full 변수 정확도:
0.8664799253034547


GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False) full 변수 정확도:
0.9365079365079365


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bytree=1, gamma=0, learning_

In [13]:
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=0)
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
df=pd.read_csv('Churn.csv')

dz=df[df.Churn> 0]
dx=df.append(dz)
print(df.shape, dz.shape, dx.shape)

#print(df.groupby('Churn').count())
dx=np.array(dx)
display(dx)
np.random.shuffle(dx)

#print(df.groupby[:,0].sum())
X=dx[:, 1:] 
y=dx[:, 0]

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=1/4)

X_train_s, y_train_s=smote.fit_sample(X_train, y_train)
#clf1 = svm.SVC()
#clf2 = GaussianNB()
clf3 = AdaBoostClassifier()
clf4 = GradientBoostingClassifier()
clf5 = XGBClassifier()
clf1 = DecisionTreeClassifier()
clf2 = RandomForestClassifier()
for i in range(1):
    X_train, X_test, y_train, y_test = train_test_split(X_train_s, y_train_s, test_size=1/4,random_state=0)
    for clf in [clf1, clf2, clf3, clf4, clf5]:
        clf.fit(X_train_s, y_train_s)
        print(clf,"full 변수 정확도:")
        print(clf.score(X_test, y_test))
        print("\n")


(3333, 17) (483, 17) (3816, 17)


array([[  0.  ,  25.  , 265.1 , ...,  11.01,   3.  ,   2.7 ],
       [  0.  ,  26.  , 161.6 , ...,  11.45,   3.  ,   3.7 ],
       [  0.  ,   0.  , 243.4 , ...,   7.32,   5.  ,   3.29],
       ...,
       [  1.  ,   0.  , 140.  , ...,   5.4 ,   4.  ,   2.62],
       [  1.  ,   0.  , 321.1 , ...,   8.12,   2.  ,   3.11],
       [  1.  ,   0.  , 118.4 , ...,  10.22,   3.  ,   3.67]])

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best') full 변수 정확도:
1.0


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False) full 변수 정확도:
0.9990627928772259




C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None) full 변수 정확도:
0.8716026241799437


GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False) full 변수 정확도:
0.9409559512652296


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bytree=1, gamma=0, learning_